# Using i386 Architecture
FROM i386/debian:jessie

RUN apt-get update -qq && \
    apt-get install -y flex \
                       bison \
                       git \
                       cmake \
                       build-essential \
                       python \
                       debhelper \
                       devscripts

ADD . /doxyparse

WORKDIR /doxyparse

ENTRYPOINT ["linux32"]
RUN ["linux32", "sh", "compile-pkg.sh"]
